application: rlc-lakeview
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /.well-known/acme-challenge/(.*)
  mime_type: text/plain
  static_files: well-known/acme-challenge/\1
  upload: well-known/acme-challenge/.*

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: public/\1
  upload: public/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: public/\1
  upload: public/(.*\.xml)
  expiration: "1h"

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: public/.*/index.html
  secure: always

- url: /(img|js|css)/(.+)
  static_files: public/\1/\2
  upload: public/(.*)
  secure: always
  expiration: "7d"

- url: /(.*)/?$
  static_files: public/\1/index.html
  upload: public/.*/index.html
  secure: always


skip_files: |
  ^(.*/)?(
  (archetypes/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (config\.yaml)|
  (config\.toml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (manage\.py)|
  (README\.md)|
  (wercker\.yml)|
  (LICENSE)|
  (content\/.*)|
  (data\/.*)|
  (static\/.*)|
  (layouts\/.*)|
  (themes\/.*)|
  (\.git\/.*)|
  (\.gitignore)|
  (_builds\/.*)|
  (_cache\/.*)|
  (_projects\/.*)|
  (_steps\/.*)|
  )$
