application: rlc-lakeview
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: public/.*/index.html
  secure: always

- url: /(.*)/?$
  static_files: public/\1/index.html
  upload: public/.*/index.html
  secure: always

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
  secure: always

skip_files: |
  ^(.*/)?(
  (archetypes/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (config\.yaml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (manage\.py)|
  (README\.md)|
  (LICENSE)|
  (content\/.*)|
  (data\/.*)|
  (static\/.*)|
  (layouts\/.*)|
  (\.git\/.*)|
  (\.gitignore)|
  )$
